apiVersion: v1
kind: Pod
metadata:
    name: api-port
    labels:
      component: web
spec:
  containers:
    - name: api-port-container
      image: dockerelvis/user-api:latest
      ports:
        - containerPort: 9003
    - name: redis-container
      image: redis
      ports:
        - containerPort: 6379


