apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: volume-claim
spec:
  accessModes:
    - ReadWriteOnce # Single node use read write
    # - ReadOnlyMany # multiple node use read
    # - ReadWriteMany # multiple node use read write
  resources:
    requests:
      storage: 1Gi